/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appujianpelatihan;

import appujianpelatihan.config.Database;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class SoalItem extends javax.swing.JFrame {

    /**
     * Creates new form SoalItem
     */
    public SoalItem() {
        initComponents();
        setTitle("Soal Ujian");
        this.setData();
        this.getCount();
    }

    Integer userId = 0;
    String userRole = "";

    public void userData(Integer id, String role) {
        this.userId = id;
        this.userRole = role;
    }

    Connection connection = Database.DBConnection();
    private PreparedStatement statement;
    int soalId = 0;
    int end = 0;
    List<appujianpelatihan.models.Soal> dataList = new ArrayList<>();

    private void getCount() {
        System.out.println(dataList.size());
        end = dataList.size();
        if (dataList.isEmpty()) {
            System.out.println("data kosong");
        } else {
            soalLabel.setText(dataList.get(0).getSoal());
            pilA.setText(dataList.get(0).getPil_a());
            pilB.setText(dataList.get(0).getPil_b());
            pilC.setText(dataList.get(0).getPil_c());
            pilD.setText(dataList.get(0).getPil_d());

            // save jawaban
//            try {
//                ButtonGroup choice = new ButtonGroup();
//                choice.add(pilA);
//                choice.add(pilB);
//                choice.add(pilC);
//                choice.add(pilD);
//                String selected = "";
//                if (pilA.isSelected()) {
//                    System.out.println(pilA.getText());
//                    selected = pilA.getText();
//                } else if (pilA.isSelected()) {
//                    System.out.println(pilB.getText());
//                    selected = pilB.getText();
//                }
//                String query = "INSERT INTO jawaban(user_id, soal_id, jawaban) values(?,?,?)";
//                statement = (PreparedStatement) connection.prepareStatement(query);
//                statement.setInt(1, userId);
//                statement.setInt(2, dataList.get(0).getId());
//                statement.setString(3, selected);
//                statement.executeUpdate();
//            } catch (SQLException e) {
//            }
        }
    }

    private void setData() {
        try {
            String query = "SELECT * FROM soal";
            statement = (PreparedStatement) connection.prepareStatement(query);
            ResultSet result = statement.executeQuery();
            while (result.next()) {
                appujianpelatihan.models.Soal soal = new appujianpelatihan.models.Soal();
                soal.setId(result.getInt("id"));
                soal.setSoal(result.getString("soal"));
                soal.setPil_a(result.getString("pil_a"));
                soal.setPil_b(result.getString("pil_b"));
                soal.setPil_c(result.getString("pil_c"));
                soal.setPil_d(result.getString("pil_d"));
                dataList.add(soal);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        soalLabel = new javax.swing.JLabel();
        pilA = new javax.swing.JRadioButton();
        pilB = new javax.swing.JRadioButton();
        pilC = new javax.swing.JRadioButton();
        pilD = new javax.swing.JRadioButton();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Soal");

        soalLabel.setText("1. Suatu langkah untuk menyelesaikan sebuah masalah secara logis dan sistematis adalah...");

        pilA.setText("Pseudocode");

        pilB.setText("Fungsi");

        pilC.setText("Array");

        pilD.setText("Algoritma");

        nextButton.setText("SELANJUTNYA");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(soalLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilA)
                    .addComponent(pilB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilC)
                    .addComponent(pilD))
                .addGap(229, 229, 229))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(325, 325, 325))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(nextButton)
                .addGap(204, 298, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(soalLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pilA)
                            .addComponent(pilC))))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pilB)
                    .addComponent(pilD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        soalId += 1;
        if (end > soalId) {
            soalLabel.setText(dataList.get(soalId).getSoal());
            pilA.setText(dataList.get(soalId).getPil_a());
            pilB.setText(dataList.get(soalId).getPil_b());
            pilC.setText(dataList.get(soalId).getPil_c());
            pilD.setText(dataList.get(soalId).getPil_d());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Anda Telah Menjawab semua soal", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            new Soal().setVisible(true);
            dispose();
        }

        // save jawaban
//        try {
//            ButtonGroup choice = new ButtonGroup();
//            choice.add(pilA);
//            choice.add(pilB);
//            choice.add(pilC);
//            choice.add(pilD);
//            if (pilA.isSelected()) {
//                System.out.println(pilA.getText());
//            } else if (pilA.isSelected()) {
//                System.out.println(pilB.getText());
//            }
//            String query = "INSERT INTO jawaban(user_id, soal_id, jawaban) values(?,?,?)";
//            statement = (PreparedStatement) connection.prepareStatement(query);
//            statement.setInt(1, userId);
//            statement.setInt(2, dataList.get(0).getId());
//            statement.setString(3, choice.getSelection().getActionCommand());
//            statement.executeUpdate();
//        } catch (SQLException e) {
//        }
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoalItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoalItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoalItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoalItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoalItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JRadioButton pilA;
    private javax.swing.JRadioButton pilB;
    private javax.swing.JRadioButton pilC;
    private javax.swing.JRadioButton pilD;
    private javax.swing.JLabel soalLabel;
    // End of variables declaration//GEN-END:variables
}
